### ISSUE TITLE
podenv gimp --shell mounts host bash

### ISSUE THREAD

**Issue by juhp** [podenv/podenv#32]
Not sure if this supported but:
```ShellSession wrap
$ (source /etc/os-release ; echo $CPE_NAME)
cpe:/o:fedoraproject:fedora:35
$ podenv gimp --shell
/data/bash: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /data/bash)
podenv: Received ExitFailure 1 when running
Raw command: podman run -i --detach-keys  -t --rm --security-opt label=disable --user 1000 --userns keep-id --network none --workdir /home/fedora --env DISPLAY=:0 --env GDK_BACKEND=wayland --env QT_QPA_PLATFORM=wayland --env WAYLAND_DISPLAY=wayland-0 --env XDG_RUNTIME_DIR=/run/user --volume /bin/bash:/data/bash --mount type=tmpfs,destination=/dev/shm --volume /etc/machine-id:/etc/machine-id --mount type=tmpfs,destination=/run/user --volume /run/user/1000/wayland-0:/run/user/wayland-0 --volume /tmp/.X11-unix:/tmp/.X11-unix --name gimp localhost/gimp /data/bash
```
I think there is no need to bind mount bash in this case.
I am not sure: is this happening in `resolveFileArgs`?

(The GLIBC_2.34 error is expected since unfortunately F35 glibc is not backwards compatible with F34 and earlier.)

**Comment by TristanCacqueray** [comment]
Oops that's unfortunate. This is happening because the `--shell` arg replace the app command with `/bin/bash` before the `hostfile` capability resolves the args, resulting in `/bin/bash` being treated as a file to be mounted in the container through the `resolveFileArgs` function.

With #33, the `--shell` arg is processed differently to avoid this issue. Thanks for the report!

**Comment by juhp** [comment]
Thanks, `--shell` works now as expected!

**Comment by TristanCacqueray** [comment]
You are welcome :-)
